spring:
  application:
    name: delivery-app

  datasource:
    username: ${DB_USERNAME}
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgresSQLDialect
server:
  port: 8081

